pipeline:

  load-cache:
    image: drillster/drone-volume-cache
    volumes: [/tmp:/cache]
    restore: true
    mount:
      - .gradle/caches
      - .gradle/wrapper

  build:
    image: openjdk:8-alpine
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew build
    when:
      event: [push,tag]

  updatesite:
    image: openjdk:8-alpine
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew updatesite
    when:
      event: [tag]

  publish:
    image: plugins/gh-pages
    username: ${GH_USER}
    password: ${GH_PASSWORD}
    pages_directory: build/public/
    secrets: [ gh_user, gh_password]
    when:
      event: tag

  save-cache:
    image: drillster/drone-volume-cache
    volumes: [/tmp:/cache]
    rebuild: true
    mount:
      - .gradle/caches
      - .gradle/wrapper

