pipeline:

  load-cache:
    image: drillster/drone-volume-cache
    volumes: [/tmp:/cache]
    restore: true
    mount:
      - .gradle/caches
      - .gradle/wrapper
      - hale

  build:
    image: eclipse-temurin:17-jdk
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - export JDK_JAVA_OPTIONS="--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED" # for Parboiled + Java17 
      - ./gradlew build
    when:
      event: [push,tag]

  updatesite:
    image: eclipse-temurin:17-jdk
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew updatesite
    when:
      event: [tag]

  publish:
    image: plugins/gh-pages
    pages_directory: build/public/
    secrets: [ github_username, github_password]
    when:
      event: [tag]

  save-cache:
    image: drillster/drone-volume-cache
    volumes: [/tmp:/cache]
    rebuild: true
    mount:
      - .gradle/caches
      - .gradle/wrapper
      - hale
